### ISSUE TITLE
Provide constructor with tagName argument

### ISSUE THREAD

**Issue by bennaux** [locked-fg/osmosis-srtm-plugin#5]
At the moment, there are 2 constructors for `SrtmPlugin_task`: One where everything can be set and one where only `localDir`, `tmp`, `localOnly` and `replaceExistingTags` can be specified, everything else comes from the properties files. 
For using the plugin as a library (like in MARiO) it would be great to have a constructor where one can specify the tagName whereas still using the standard server settings.
At the moment, with an ASTER plugin in development, MARiO uses both `height` and `ele`, but in some maps there already are some `ele` tags.

**Comment by locked-fg** [comment]
Sounds reasonable, can you provide a patch / pull request?

**Comment by bennaux** [comment]
I'll try. This is my first day on github... ;-) If it works, I will also move my ASTER plugin (based on your SRTM ~) to github.

**Comment by locked-fg** [comment]
Don't worry. Just change the code and create a patch (should be easy. Almost every Ide helps you in this case) and send it to me
