### ISSUE TITLE
Method of calculating elevation value

### ISSUE THREAD

**Issue by nikolauskrismer** [locked-fg/osmosis-srtm-plugin#8]
I've got a question about the way the height value is retrieved from the matching SRTM tile.
The code I am referring to is this one:
https://github.com/locked-fg/osmosis-srtm-plugin/blob/fe58ab4a099fdde6a6c8db5b1598ebda5fe107d5/src/main/java/de/locked/osmosis/srtmplugin/SrtmPlugin_task.java#L273-286

Am I right that this is a weighted mean calculation?
If so, why are there only 4 srtm values included (I would have expected 5).

Isn't the elevation retrieved by ``getValues(file, rowmin - 1, colmin - 1);`` missing (maybe this would be stored into values[4]?? Am I missing something here??

**Comment by locked-fg** [comment]
Why do you expect 5 values? If I remember correctly, the values are taken from the 4 nearby edges. The weights should be depending on the distance to the respective edge.

**Comment by nikolauskrismer** [comment]
I'd expect 5 values, because I'd expect the following.
Given this "image":

    | v00 | v01 | v02 |
    | v10 | v11 | v12 |
    | v20 | v21 | v22 |

Assume you want to get the value at v11.
At the moment you are using v10, v11, v12 and v21 to do this. Why are you leaving out v01???

When using only 4 values it would seem more natural to me to use v01, v10, v12 and v21, but again... this leaves the question why you would completely forget about v11 (however, maybe that's ok of v11 is a void or known to be off by far)

Why would you only use 4 values?

**Comment by locked-fg** [comment]
Ahh now I see! I guess we have a different understanding of the data. Let me line out my point of view:
SRTM data is organized in a grid with a certain resolution ([SRTM-90](http://www.cgiar-csi.org/data/srtm-90m-digital-elevation-database-v4-1) for example has a 90m resolution at the equator) . So you have measures on the nodes of a grid only (lines along latitudes and longitudes).
Each node is identified by latitude/longitude coordinates plus of course the elevation data:
```
| v00 | ___ | v02 | ___ | v03
| ___ | v11 | ___ | ___ | ___ | <- no data between ror v0. and v2.
| v20 | ___ | v22 | ___ | v23 |
         ^-- no data between columns v.0 and v.2  
```
If you want the data for v11, we linearly interpolated from the 4 surrounding edges.

In the case you outlined, v11 must be present in the data anyways, as it would be a node (with other nodes being directly above/below/asides).

**Comment by nikolauskrismer** [comment]
Ok... true... that makes sense :+1: 
Thanks for the explanation!
